Fix module path for Swift 6 builds
When building with swift 6, Danger's
- Danger*.abi.json
- **Danger*.swiftmodule**
- Danger*.swiftdoc
- Danger*.swiftsourceinfo
are now located in `.build/debug/Modules` location instead of `.build/debug/` module.

With swift 6 `SwiftFormat` generates two module maps `SwiftFormat.build` & `SwiftFormat-tool.build`. at `.build/debug/`.
Which cause `- error: redefinition of module 'SwiftFormat'`

This change conditionally update swift's import search path to `.build/debug/Modules` to address both issues.